### ISSUE TITLE
Email regex

### ISSUE THREAD

**Issue by Tavorick** [Frederikam/Screeps-Script-Downloader#1]
Hi,

Thank you for providing this awesome tool :) 
In trying it out i did find a tiny issue: When entering an email like john.smith@example.com the program marks the email as invalid because of the "." between john and smith.

I fixed this by simply replacing the regex pattern you use in file Downloader.js to : Pattern EMAIL_PATTERN = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);

I just wanted to share my solution with you, feel free to do whatever you like with it.
Keep up the good work!

Kind regards,
Tavorick

**Comment by freyacodes** [comment]
Thanks for the heads up. I wasn't aware that my regex didn't match emails with dots in them. I'll release a patch in a moment
